# These are supported funding model platforms
# https://help.github.com/cn/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository
# github: [AriaLyy]
patreon: AriaLyy
liberapay: Aria
custom: ["https://afdian.net/@arialyy/plan"]

